mytestsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("rensyu/", include("rensyu.urls")),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

# 어플리케이션이 여러개 있을때 해당 어플리케이션을 특정하기 위한 namespace를 지정
app_name = "polls"
urlpatterns = [
    # # ex: /polls/
    # path("", views.index, name="index"),
    # # ex: /polls/5/
    # path("<int:question_id>/", views.detail, name="detail"),
    # # ex: /polls/5/results/
    # path("<int:question_id>/results/", views.results, name="results"),
    # # ex: /polls/5/vote/
    # path("<int:question_id>/vote/", views.vote, name="vote"),


    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    
]

rensyu/urls.py
from django.urls import path

from .views import views
from .views import views_tdColor

# 어플리케이션이 여러개 있을때 해당 어플리케이션을 특정하기 위한 namespace를 지정
app_name = "rensyu"
urlpatterns = [
    # 인덱스 /rensyu/
    path("", views.index, name="index"),

    # 전통색 /rensyu/tdcolor/
    path("tdcolor/", views_tdColor.tdcolor, name="tdcolor"),

    # 유저관리 /rensyu/userlist/
    path("userlist/", views.userList, name="userList"),

    # 유저관리 - 상세정보 /rensyu/userlist/detail/
    path("userlist/detail/<int:id>", views.userDetail, name="userDetail"),

    # 유저관리 - 수정 /rensyu/userlist/modify/1
    path("userlist/modify/<int:id>", views.userModify, name="userModify"),

    # 유저관리 - 수정 /rensyu/userlist/modify/1/upd
    path("userlist/modify/<int:id>/upd", views.updateUserData, name="updateUserData"),

    # 유저관리 - 수정 /rensyu/userlist/create/
    path("userlist/create/", views.userCreate, name="userCreate"),

    # 유저관리 - 삭제 /rensyu/userlist/delete/1
    path("userlist/delete/<int:id>", views.userDelete, name="userDelete"),

    # # ex: /polls/5/
    # path("<int:question_id>/", views.detail, name="detail"),
    # # ex: /polls/5/results/
    # path("<int:question_id>/results/", views.results, name="results"),
    # # ex: /polls/5/vote/
    # path("<int:question_id>/vote/", views.vote, name="vote"),


    # path("", views.IndexView.as_view(), name="index"),
    # path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    # path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    # path("<int:question_id>/vote/", views.vote, name="vote"),
    
]

rensyu/models.py
from django.db import models

# python manage.py makemigrations을 통해 이 변경사항에 대한 마이그레이션을 만드세요.
# python manage.py migrate 명령을 통해 변경사항을 데이터베이스에 적용하세요.


"""
한국의 전통색
"""
# 전통색 관리 테이블
class TranditionalColor(models.Model):
    color_name = models.CharField(max_length=50
                                  , help_text="색깔 이름")
    category_code = models.CharField(max_length=4
                                     ,help_text="카테고리 코드")
    rgb_code = models.CharField(max_length=6
                                , help_text="rgb 코드")
    r_num = models.IntegerField(help_text="r값")
    g_num = models.IntegerField(help_text="g값")
    b_num = models.IntegerField(help_text="b값")
    cymk_code = models.CharField(max_length=15
                                 , help_text="cymk 코드")

    def __str__(self) -> str:
        return self.color_name + " : " + self.rgb_code
    def getCategoryName(self) :
        # 카테고리명 관리테이블의 카테고리코드와 일치하는 카테고리명칭 반환
        return TranditionalColorCategory.objects.get(pk = self.category_code).category_name

# 전통색의 카테고리명 관리 테이블
class TranditionalColorCategory(models.Model):
    category_code = models.CharField(primary_key=True, max_length=4) # 카테고리 코드 ex) 0001
    category_name = models.CharField(max_length=50) # 카테고리 명칭 ex) 무채색계(無彩色界)

    def __str__(self) -> str:
        return self.category_name



"""
유저관리 CRUD 테스트
"""

# 性別
CODE_GENDER = 2
# 血液型
CODE_BLOOD_TYPE = 3

# コードリスト
class CodeList(models.Model):
    code = models.CharField(max_length=4, unique=True) # 코드 ex) 0001
    code_name = models.CharField(max_length=100) # 코드명칭 ex) 성별
    code_description = models.CharField(max_length=1000) # 코드관련 설명 ex) 성별 관리용 코드, 남/여/기타등으로 데이터를 관리.

    def __str__(self) -> str:
        return self.code_name
    

# コード管理
# 장고 모델에서는 single-column primary key만을 지원하므로 unique제약조건을 이용하여 복수칼럼에 대한 제약을 걸 수 밖에 없다고 한다.
class CodeManage(models.Model): 
    code_subcode = models.CharField(max_length=4) # 코드 ex) (0001)0001
    code_subname = models.CharField(max_length=100) # 코드 ex) (0001)0001 男
    codelist = models.ForeignKey(CodeList, on_delete=models.CASCADE)

    # class Meta:
    #     constraints = [
    #         models.UniqueConstraint(
    #             fields=['code', 'code_subcode'], name='CodeManage_constraints_1'
    #         )
    #         # models.ForeignKey("rensyu.CodeList", verbose_name=("code"), on_delete=models.CASCADE)
    #     ]

# ユーザーリスト
class UserList(models.Model):
    kanzi_name = models.CharField(max_length=50) #이름(한자)
    kana_name = models.CharField(max_length=60) #이름(카나)
    age = models.IntegerField() # 연령
    birthdate = models.DateField() # 생일
    gender = models.CharField(max_length=4) # 관리코드 0001
    blood_type = models.CharField(max_length=4) # 관리코드 0002
    mail_address = models.CharField(max_length=100)
    tel_num = models.CharField(max_length=15)
    mobile_tel_num = models.CharField(max_length=15)
    post_num = models.CharField(max_length=15)
    address = models.CharField(max_length=200)
    company_name = models.CharField(max_length=50)

    # TODO update_date 추가하기
    # TODO create_date 추가하기 default가 date.now()

    def gender_text(self) :
        # 성별의 명칭 취득하기처리
        return CodeList.objects.get(pk=CODE_GENDER).codemanage_set.get(code_subcode=self.gender).code_subname
    
    def blood_type_text(self) :
        # 성별의 명칭 취득하기처리
        return CodeList.objects.get(pk=CODE_BLOOD_TYPE).codemanage_set.get(code_subcode=self.gender).code_subname

rensyu/views/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from ..models import UserList

# Create your views here.
# index
def index(request):

    context = {
        "date" : timezone.now(),
    }
    return render(request, 'rensyu/index.html', context)
    # return HttpResponse("Hello, world. You're at the polls index.")


# 유저관리 페이지
def userList(request):
    # 유저리스트 가져오기
    user_list = UserList.objects.all()

    # userlistObj = UserList.objects.create(kanzi_name="鈴木 由紀",kana_name="すずき ゆき", age="33", birthdate="1990-05-17", gender="0002", blood_type="0001", mail_address="suzukiyuki@example.ne.jp", tel_num="093-529-8413", mobile_tel_num="080-0844-9365", post_num="834-8774", address="福岡県北九州市小倉北区下富野2-2-304", company_name="株式会社H＆K")
    # print(userlistObj)
    context = {
        "user_list" : user_list
    }
    return render(request, 'rensyu/userlist/list.html', context)

# 유저관리 상세
def userDetail(request, id):
    
    # 유저관리 테이블의 id로 데이터 취득
    user_data = get_object_or_404(UserList, pk=id)
    
    context = {
        "user_data" : user_data
    }
    return render(request, 'rensyu/userlist/detail.html', context)

# 유저관리 상세
def userModify(request, id):
    # 유저관리 테이블의 id로 데이터 취득
    user_data = get_object_or_404(UserList, pk=id)
    
    # 수정용 화면으로
    context = {
        "user_data" : user_data
    }
    return render(request, 'rensyu/userlist/modify.html', context)


# 수정내용 등록
def updateUserData(request, id) :
    # 유저관리 테이블의 id로 데이터 취득
    user_data = get_object_or_404(UserList, pk=id)

    # TODO validate

    # 입력된 데이터로 변경
    user_data.kanzi_name = request.POST["kanzi_name"]


    # TODO updated_date 수정하기
    user_data.save()

    # detail 페이지로 이동하기
    return HttpResponseRedirect(reverse("rensyu:userDetail", args=(user_data.id,)))

# 유저관리 데이터 생성하기
def userCreate(request):
    # 유저 작성 페이지
    context = {
        # "user_list" : user_list
    }
    return render(request, 'rensyu/userlist/create.html', context)

# 유저관리 데이터 삭제
def userDelete(request, id):
    # 데이터 조회
    user_data = get_object_or_404(UserList, pk=id)
    print(user_data)

    # 해당데이터 삭제하기
    user_data.delete()

    return HttpResponseRedirect(reverse("rensyu:userList")) # "/polls/3/results/"

rensyu/views/views_tdColor.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.http import HttpResponse

from ..models import TranditionalColor

# 전통색
def tdcolor(request):
    # 컬러 전부 가져오기
    color_list = TranditionalColor.objects.all().order_by("id") 
    context = {
        "date" : timezone.now(),
        "color_list" : color_list
    }
    return render(request, 'rensyu/tranditionalColor.html', context)

rensyu/templates/rensyu/header.html
{% load static %}

<!-- TODO 헤더 꾸미기 nav? menu디자인 확인 필요 -->
<div class="common-header">
  <a href="{% url 'rensyu:tdcolor' %}">한국의 전통색</a><br>
  <a href="{% url 'rensyu:userList' %}">유저관리</a>
</div>

rensyu/templates/rensyu/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>

  <link rel="stylesheet" href="{% static 'rensyu/css/index.css' %}">
  <script src="{% static 'rensyu/js/index.js' %}"></script>

</head>
<body>
  <div class="">
    <h1>django 어플리케이션</h1>
      <div>{{ date }}</div>
      <ul>
        <li><a href="{% url 'rensyu:tdcolor' %}">한국의 전통색</a></li>
        <details>전통색을 시각화하려면...</details>
        <li><a href="{% url 'rensyu:userList' %}">유저 정보 관리 페이지</a></li>
        <details>유저 작성, 확인, 수정, 삭제</details>
      </ul>
    
  </div>
</body>

</html>

rensyu/templates/rensyu/static_header.html
{% load static %}


<!-- style sheet START -->
<link rel="stylesheet" href="{% static 'rensyu/css/reset.css' %}">

<!-- google font -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Noto+Serif+KR:wght@700&display=swap" rel="stylesheet">
<!-- style sheet END -->

<!-- js START -->
<!-- jquery -->
<script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM="
    crossorigin="anonymous"></script>

<!-- common -->
<script src="{% static 'rensyu/js/common.js' %}"></script>

<!-- js END -->

rensyu/templates/rensyu/tranditionalColor.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>

  {% include "rensyu/static_header.html" %}

  <!-- jquery -->
  <!-- <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM="
    crossorigin="anonymous"></script> -->

  <!-- google font -->
  <!-- <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+KR:wght@700&display=swap" rel="stylesheet"> -->

  <link rel="stylesheet" href="{% static 'rensyu/css/tranditionalColor.css' %}">
  <script src="{% static 'rensyu/js/tranditionalColor.js' %}"></script>
</head>
<body>
  {% include "rensyu/header.html" %}
  <main>
    <div class="flex-container">
      <div class="show-box">
        <div class="show-box-text">
          <h1>
            한국의 전통색상
          </h1>
          <!-- 색 이름 표시 -->
          <h3>
            &nbsp;
          </h3>
          <div class="show-box-detail">
            <span style="color:red">R</span>ed
            <div class="detail-bar">
              <div class="detail-r-num">
                
              </div>
            </div>
            <span style="color:green">G</span>reen
            <div class="detail-bar">
              <div class="detail-g-num">
                
              </div>
            </div>
            <span style="color:blue">B</span>lue
            <div class="detail-bar">
              <div class="detail-b-num">
                
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="color-div">
        <ul class="color-list">
        {% if color_list %}
          {% for item in color_list %}
          <li>
            <div class="color-box" data-rgb={{item.rgb_code}} data-rnum={{item.r_num}} data-gnum={{item.g_num}} data-bnum={{item.b_num}}>
              <div class="color-box-thumb-col" style="background-color: #{{item.rgb_code}};"></div>
              <div class="color-box-detail">{{item.color_name}} {{item.getCategoryName}}</div>
            </div>
          </li>
          {% endfor %}

        {% endif %}
          <!--<li>
            <div class="color-box" data-rgb="1D1E23">
              <div class="color-box-thumb-col" style="background-color: #1D1E23;"></div>
              <div class="color-box-detail">흑백</div>
            </div>
          </li>-->
        </ul>
      </div>
    </div>
  </main>
  <footer></footer>
</body>
</html>