mytestsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("rensyu/", include("rensyu.urls")),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

# 어플리케이션이 여러개 있을때 해당 어플리케이션을 특정하기 위한 namespace를 지정
app_name = "polls"
urlpatterns = [
    # # ex: /polls/
    # path("", views.index, name="index"),
    # # ex: /polls/5/
    # path("<int:question_id>/", views.detail, name="detail"),
    # # ex: /polls/5/results/
    # path("<int:question_id>/results/", views.results, name="results"),
    # # ex: /polls/5/vote/
    # path("<int:question_id>/vote/", views.vote, name="vote"),


    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    
]

rensyu/urls.py
from django.urls import path

from .views import views
from .views import views_tdColor

# 어플리케이션이 여러개 있을때 해당 어플리케이션을 특정하기 위한 namespace를 지정
app_name = "rensyu"
urlpatterns = [
    # 인덱스 /rensyu/
    path("", views.index, name="index"),

    # 전통색 /rensyu/tdcolor/
    path("tdcolor/", views_tdColor.tdcolor, name="tdcolor"),

    # 유저관리 /rensyu/userlist/
    path("userlist/", views.userList, name="userList"),

    # 유저관리 - 상세정보 /rensyu/userlist/detail/
    path("userlist/detail/<int:id>", views.userDetail, name="userDetail"),

    # 유저관리 - 수정 /rensyu/userlist/modify/1
    path("userlist/modify/<int:id>", views.userModify, name="userModify"),

    # 유저관리 - 수정 /rensyu/userlist/modify/1/upd
    path("userlist/modify/<int:id>/upd", views.updateUserData, name="updateUserData"),

    # 유저관리 - 수정 /rensyu/userlist/create/
    path("userlist/create/", views.userCreate, name="userCreate"),

    # 유저관리 - 삭제 /rensyu/userlist/delete/1
    path("userlist/delete/<int:id>", views.userDelete, name="userDelete"),

    # # ex: /polls/5/
    # path("<int:question_id>/", views.detail, name="detail"),
    # # ex: /polls/5/results/
    # path("<int:question_id>/results/", views.results, name="results"),
    # # ex: /polls/5/vote/
    # path("<int:question_id>/vote/", views.vote, name="vote"),


    # path("", views.IndexView.as_view(), name="index"),
    # path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    # path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    # path("<int:question_id>/vote/", views.vote, name="vote"),
    
]

rensyu/models.py
from django.db import models

# python manage.py makemigrations을 통해 이 변경사항에 대한 마이그레이션을 만드세요.
# python manage.py migrate 명령을 통해 변경사항을 데이터베이스에 적용하세요.


"""
한국의 전통색
"""
# 전통색 관리 테이블
class TranditionalColor(models.Model):
    color_name = models.CharField(max_length=50
                                  , help_text="색깔 이름")
    category_code = models.CharField(max_length=4
                                     ,help_text="카테고리 코드")
    rgb_code = models.CharField(max_length=6
                                , help_text="rgb 코드")
    r_num = models.IntegerField(help_text="r값")
    g_num = models.IntegerField(help_text="g값")
    b_num = models.IntegerField(help_text="b값")
    cymk_code = models.CharField(max_length=15
                                 , help_text="cymk 코드")

    def __str__(self) -> str:
        return self.color_name + " : " + self.rgb_code
    def getCategoryName(self) :
        # 카테고리명 관리테이블의 카테고리코드와 일치하는 카테고리명칭 반환
        return TranditionalColorCategory.objects.get(pk = self.category_code).category_name

# 전통색의 카테고리명 관리 테이블
class TranditionalColorCategory(models.Model):
    category_code = models.CharField(primary_key=True, max_length=4) # 카테고리 코드 ex) 0001
    category_name = models.CharField(max_length=50) # 카테고리 명칭 ex) 무채색계(無彩色界)

    def __str__(self) -> str:
        return self.category_name



"""
유저관리 CRUD 테스트
"""

# 性別
CODE_GENDER = 2
# 血液型
CODE_BLOOD_TYPE = 3

# コードリスト
class CodeList(models.Model):
    code = models.CharField(max_length=4, unique=True) # 코드 ex) 0001
    code_name = models.CharField(max_length=100) # 코드명칭 ex) 성별
    code_description = models.CharField(max_length=1000) # 코드관련 설명 ex) 성별 관리용 코드, 남/여/기타등으로 데이터를 관리.

    def __str__(self) -> str:
        return self.code_name
    

# コード管理
# 장고 모델에서는 single-column primary key만을 지원하므로 unique제약조건을 이용하여 복수칼럼에 대한 제약을 걸 수 밖에 없다고 한다.
class CodeManage(models.Model): 
    code_subcode = models.CharField(max_length=4) # 코드 ex) (0001)0001
    code_subname = models.CharField(max_length=100) # 코드 ex) (0001)0001 男
    codelist = models.ForeignKey(CodeList, on_delete=models.CASCADE)

    # class Meta:
    #     constraints = [
    #         models.UniqueConstraint(
    #             fields=['code', 'code_subcode'], name='CodeManage_constraints_1'
    #         )
    #         # models.ForeignKey("rensyu.CodeList", verbose_name=("code"), on_delete=models.CASCADE)
    #     ]

# ユーザーリスト
class UserList(models.Model):
    kanzi_name = models.CharField(max_length=50) #이름(한자)
    kana_name = models.CharField(max_length=60) #이름(카나)
    age = models.IntegerField() # 연령
    birthdate = models.DateField() # 생일
    gender = models.CharField(max_length=4) # 관리코드 0001
    blood_type = models.CharField(max_length=4) # 관리코드 0002
    mail_address = models.CharField(max_length=100)
    tel_num = models.CharField(max_length=15)
    mobile_tel_num = models.CharField(max_length=15)
    post_num = models.CharField(max_length=15)
    address = models.CharField(max_length=200)
    company_name = models.CharField(max_length=50)

    # TODO update_date 추가하기
    # TODO create_date 추가하기 default가 date.now()

    def gender_text(self) :
        # 성별의 명칭 취득하기처리
        return CodeList.objects.get(pk=CODE_GENDER).codemanage_set.get(code_subcode=self.gender).code_subname
    
    def blood_type_text(self) :
        # 성별의 명칭 취득하기처리
        return CodeList.objects.get(pk=CODE_BLOOD_TYPE).codemanage_set.get(code_subcode=self.gender).code_subname

rensyu/views/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from ..models import UserList

# Create your views here.
# index
def index(request):

    context = {
        "date" : timezone.now(),
    }
    return render(request, 'rensyu/index.html', context)
    # return HttpResponse("Hello, world. You're at the polls index.")


# 유저관리 페이지
def userList(request):
    # 유저리스트 가져오기
    user_list = UserList.objects.all()

    # userlistObj = UserList.objects.create(kanzi_name="鈴木 由紀",kana_name="すずき ゆき", age="33", birthdate="1990-05-17", gender="0002", blood_type="0001", mail_address="suzukiyuki@example.ne.jp", tel_num="093-529-8413", mobile_tel_num="080-0844-9365", post_num="834-8774", address="福岡県北九州市小倉北区下富野2-2-304", company_name="株式会社H＆K")
    # print(userlistObj)
    context = {
        "user_list" : user_list
    }
    return render(request, 'rensyu/userlist/list.html', context)

# 유저관리 상세
def userDetail(request, id):
    
    # 유저관리 테이블의 id로 데이터 취득
    user_data = get_object_or_404(UserList, pk=id)
    
    context = {
        "user_data" : user_data
    }
    return render(request, 'rensyu/userlist/detail.html', context)

# 유저관리 상세
def userModify(request, id):
    # 유저관리 테이블의 id로 데이터 취득
    user_data = get_object_or_404(UserList, pk=id)
    
    # 수정용 화면으로
    context = {
        "user_data" : user_data
    }
    return render(request, 'rensyu/userlist/modify.html', context)


# 수정내용 등록
def updateUserData(request, id) :
    # 유저관리 테이블의 id로 데이터 취득
    user_data = get_object_or_404(UserList, pk=id)

    # TODO validate

    # 입력된 데이터로 변경
    user_data.kanzi_name = request.POST["kanzi_name"]


    # TODO updated_date 수정하기
    user_data.save()

    # detail 페이지로 이동하기
    return HttpResponseRedirect(reverse("rensyu:userDetail", args=(user_data.id,)))

# 유저관리 데이터 생성하기
def userCreate(request):
    # 유저 작성 페이지
    context = {
        # "user_list" : user_list
    }
    return render(request, 'rensyu/userlist/create.html', context)

# 유저관리 데이터 삭제
def userDelete(request, id):
    # 데이터 조회
    user_data = get_object_or_404(UserList, pk=id)
    print(user_data)

    # 해당데이터 삭제하기
    user_data.delete()

    return HttpResponseRedirect(reverse("rensyu:userList")) # "/polls/3/results/"

rensyu/views/views_tdColor.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.http import HttpResponse

from ..models import TranditionalColor

# 전통색
def tdcolor(request):
    # 컬러 전부 가져오기
    color_list = TranditionalColor.objects.all().order_by("id") 
    context = {
        "date" : timezone.now(),
        "color_list" : color_list
    }
    return render(request, 'rensyu/tranditionalColor.html', context)

rensyu/templates/rensyu/userlist/create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>유저 작성하기</title>
</head>
<body>
  
</body>
</html>

rensyu/templates/rensyu/userlist/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>유저 상세정보</title>
</head>
<body>
  <table>
    <tr>
      <td>ID</td>
      <td>{{ user_data.id }}</td>
    </tr>
    <tr>
      <td>漢字氏名</td>
      <td>{{ user_data.kanzi_name }}</td>
    </tr>
    <tr>
      <td>かな氏名</td>
      <td>{{ user_data.kana_name }}</td>
    </tr>
    <tr>
      <td>年齢</td>
      <td>{{ user_data.age }}</td>
    </tr>
    <tr>
      <td>誕生日</td>
      <td>{{ user_data.birthdate }}</td>
    </tr>
    <tr>
      <td>性別</td>
      <td>{{ user_data.gender_text }}</td>
    </tr>
    <tr>
      <td>血液型</td>
      <td>{{ user_data.blood_type_text }}</td>
    </tr>
    <tr>
      <td>メールアドレス</td>
      <td>{{ user_data.mail_address }}</td>
    </tr>
    <tr>
      <td>電話番号</td>
      <td>{{ user_data.tel_num }}</td>
    </tr>
    <tr>
      <td>携帯電話番号</td>
      <td>{{ user_data.mobile_tel_num }}</td>
    </tr>
    <tr>
      <td>郵便番号</td>
      <td>{{ user_data.post_num }}</td>
    </tr>
    <tr>
      <td>住所</td>
      <td>{{ user_data.address }}</td>
    </tr>
    <tr>
      <td>会社名</td>
      <td>{{ user_data.company_name }}</td>
    </tr>
  </table>
  
  
</body>
</html>

rensyu/templates/rensyu/userlist/list.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  {% include "rensyu/static_header.html" %}

  <script src="{% static 'rensyu/js/userlist/list.js' %}"></script>

  <title>유저 리스트</title>
</head>

<body>
  {% include "rensyu/header.html" %}

  <button onClick="alert('create')">신규작성</button>
  <button onClick="alert('export')">excel export</button>
  <button onClick="alert('import')">excel import</button>
  <input type="text">
  <button onClick="alert('search')">검색하기</button>
  
  <table>
    <tr>
      <th>이름</th>
      <th>가나</th>
      <th>나이</th>
      <th>생일</th>
      <th>성별</th>
      <th>혈액형</th>
      <!--<th>이메일</th>
      <th>전화번호</th>
      <th>휴대전화</th>
      <th>우편번호</th>
      <th>주소</th>
      <th>회사명</th>-->
      <th></th>
    </tr>
    {% for item in user_list %}
    <tr>
      <td>{{ item.id }} {{ item.kanzi_name }}</td>
      <td>{{ item.kana_name }}</td>
      <td>{{ item.age }}</td>
      <td>{{ item.birthdate }}</td>
      <td>{{ item.gender_text }}</td>
      <td>{{ item.blood_type_text }}</td>
      <!--<td>{{ item.mail_address }}</td>
      <td>{{ item.tel_num }}</td>
      <td>{{ item.mobile_tel_num }}</td>
      <td>{{ item.post_num }}</td>
      <td>{{ item.address }}</td>
      <td>{{ item.company_name }}</td>-->
      <td>
        <button onClick="location.href='{% url 'rensyu:userDetail' item.id %}'">상세정보</button>
        <button onClick="location.href='{% url 'rensyu:userModify' item.id %}'">수정</button>
        <button class="del_item" data-id={{ item.id }} data-url={% url 'rensyu:userDelete' item.id %}>삭제</button>
      </td>
    </tr>
    {% endfor %}
  </table>

</body>

</html>

rensyu/templates/rensyu/userlist/modify.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  데이터 수정하기
  
  <form action="{% url 'rensyu:updateUserData' user_data.id %}" method="post">
    {% csrf_token %}
    이름
    <table>
      <tr>
        <td>ID</td>
        <td>{{ user_data.id }}</td>
      </tr>
      <tr>
        <td>漢字氏名</td>
        <td>
          <input type="text" name="kanzi_name" id="kanzi_name" value='{{ user_data.kanzi_name }}'>
        </td>
      </tr>
      <tr>
        <td>かな氏名</td>
        <td>
          <input type="text" name="kana_name" id="kana_name" value='{{ user_data.kana_name }}'>
        </td>
      </tr>
      <!-- <tr>
        <td>年齢</td>
        <td>
          <input type="text" name="age" id="age" value={{ user_data.age }}>
        </td>
      </tr>
      <tr>
        <td>誕生日</td>
        <td>
          TODO datepicker
          {{ user_data.birthdate }}
        </td>
      </tr>
      <tr>
        <td>性別</td>
        <td>
          TODO SELECT 코드로 어떻게 안되나
          {{ user_data.gender_text }}
        </td>
      </tr>
      <tr>
        <td>血液型</td>
        <td>
          TODO SELECT 코드로 어떻게 안되나
          {{ user_data.blood_type_text }}
        </td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td>
          <input type="text" name="mail_address" id="mail_address" value={{ user_data.mail_address }}>
        </td>
      </tr>
      <tr>
        <td>電話番号</td>
        <td>
          <input type="text" name="tel_num" id="tel_num" value={{ user_data.tel_num }}>
        </td>
      </tr>
      <tr>
        <td>携帯電話番号</td>
        <td>
          <input type="text" name="mobile_tel_num" id="mobile_tel_num" value={{ user_data.mobile_tel_num }}>
        </td>
      </tr>
      <tr>
        <td>郵便番号</td>
        <td>
          <input type="text" name="post_num" id="post_num" value={{ user_data.post_num }}>
        </td>
      </tr>
      <tr>
        <td>住所</td>
        <td>
          <input type="text" name="address" id="address" value={{ user_data.address }}>
        </td>
      </tr>
      <tr>
        <td>会社名</td>
        <td>
          <input type="text" name="company_name" id="company_name" value={{ user_data.company_name }}>
        </td>
      </tr> -->
    </table>

    
    <button type="submit">수정하기</button>
    <!-- TODO 뒤로가기? 목록으로 돌아가기? -->
    <button>취소</button>
  </form>
  

  
</body>
</html>

rensyu/templates/rensyu/userlist/userList.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>유저 리스트</title>
</head>

<body>
  <table>
    <tr>
      <th>이름</th>
      <th>가나</th>
      <th>나이</th>
      <th>생일</th>
      <th>성별</th>
      <th>혈액형</th>
      <th>이메일</th>
      <th>전화번호</th>
      <th>휴대전화</th>
      <th>우편번호</th>
      <th>주소</th>
      <th>회사명</th>
      <th></th>
    </tr>
    {% for item in user_list %}
    <tr>
      <td>{{ item.id }} {{ item.kanzi_name }}</td>
      <td>{{ item.kana_name }}</td>
      <td>{{ item.age }}</td>
      <td>{{ item.birthdate }}</td>
      <td>{{ item.gender }}</td>
      <td>{{ item.blood_type }}</td>
      <td>{{ item.mail_address }}</td>
      <td>{{ item.tel_num }}</td>
      <td>{{ item.mobile_tel_num }}</td>
      <td>{{ item.post_num }}</td>
      <td>{{ item.address }}</td>
      <td>{{ item.company_name }}</td>
      <td>
        <button onClick="location.href='{% url 'rensyu:userDetail' item.id %}'">상세정보</button>
        <button onClick="location.href='{% url 'rensyu:userModify' item.id %}'">수정</button>
        <button onClick="alert('del')">삭제</button>
      </td>
    </tr>
    {% endfor %}
  </table>

</body>

</html>

rensyu/templates/rensyu/userlist/usercreate.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>유저 작성하기</title>
</head>
<body>
  
</body>
</html>

rensyu/templates/rensyu/userlist/userdetail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>유저 상세정보</title>
</head>
<body>
  <table>
    <tr>
      <td>ID</td>
      <td>{{ user_data.id }}</td>
    </tr>
    <tr>
      <td>漢字氏名</td>
      <td>{{ user_data.kanzi_name }}</td>
    </tr>
    <tr>
      <td>かな氏名</td>
      <td>{{ user_data.kana_name }}</td>
    </tr>
    <tr>
      <td>年齢</td>
      <td>{{ user_data.age }}</td>
    </tr>
    <tr>
      <td>誕生日</td>
      <td>{{ user_data.birthdate }}</td>
    </tr>
    <tr>
      <td>性別</td>
      <td>{{ user_data.gender }}</td>
    </tr>
    <tr>
      <td>血液型</td>
      <td>{{ user_data.blood_type }}</td>
    </tr>
    <tr>
      <td>メールアドレス</td>
      <td>{{ user_data.mail_address }}</td>
    </tr>
    <tr>
      <td>電話番号</td>
      <td>{{ user_data.tel_num }}</td>
    </tr>
    <tr>
      <td>携帯電話番号</td>
      <td>{{ user_data.mobile_tel_num }}</td>
    </tr>
    <tr>
      <td>郵便番号</td>
      <td>{{ user_data.post_num }}</td>
    </tr>
    <tr>
      <td>住所</td>
      <td>{{ user_data.address }}</td>
    </tr>
    <tr>
      <td>会社名</td>
      <td>{{ user_data.company_name }}</td>
    </tr>
  </table>
  
  
</body>
</html>